### ISSUE TITLE
Ability to emulate device existence

### ISSUE THREAD

**Issue by xrh0905** [BryanJacobs/fido2-hid-bridge#8]
Hi. Nice work, successful use it to make fido2 login on my Ubuntu VM.
However, it looks like the device constantly emulate an Fido device even when there is no Smartcard insert or even no PCSC reader present. It cause the login page to hang until the application's communication timeout reached.
Is it possible for the bridge to only begin emulation until there is a valid Smartcard inserted?

**Comment by BryanJacobs** [comment]
Yes, it's possible, but if it were to do that you wouldn't have the opportunity to insert your smartcard in response to an auth prompt.

With software that expects HID tokens, the logic is "if there's a smartcard present, prompt the user to authenticate with it". So if this bridge doesn't emulate an inserted token, you'll just see an auth failure unless your card is already in/on the reader when you visit the login page.

**Comment by xrh0905** [comment]
Got it. The reason I ask this is that when using pam_u2f.so, the login page simply hang when enter the login process(click on avatar, and blank screen for 30 second until PCSC timeout reached) which is quite annoying. So I guess it's actually a
issue with pam_u2f, not this application? 
Also, in Windows, if there is no token exist, it will block the authication process and prompt to insert/tap security key. I thought it's in the standard but for now maybe the true is that it's Windows specific...

**Comment by BryanJacobs** [comment]
> Got it. The reason I ask this is that when using pam_u2f.so, the login page simply hang when enter the login process(click on avatar, and blank screen for 30 second until PCSC timeout reached) which is quite annoying. So I guess it's actually a issue with pam_u2f, not this application? Also, in Windows, if there is no token exist, it will block the authication process and prompt to insert/tap security key. I thought it's in the standard but for now maybe the true is that it's Windows specific...

Totally up to the software.

Personally I use https://github.com/BryanJacobs/FIDOk/ for gatewaying now, and that's where my (very limited) development effort is going. There's just too much stuff that needs to be better supported in the FIDO ecosystem...

**Comment by xrh0905** [comment]
Understand. Thanks for your work anyway.
